### ISSUE TITLE
Using the ABCCheckParticles class should not require pytables to be available

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#101]
There are a number of places where the pytables Records are used, thus currently pytables needs to be installed in order to be able to user the testing templates. However, it should be possible to avoid this.

**Comment by nathanfranklin** [comment]
:+1:

**Comment by itziakos** [comment]
@roigcarlo, this issue is addressed in #106, so I added it in the 0.1.1 milestone

**Comment by roigcarlo** [comment]
:+1:

**Comment by itziakos** [comment]
implemented in #106
