### ISSUE TITLE
update_bond and update_particles should raise KeyError

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#104]
in Particles, the `update_bond` and `update_particles` methods raise ValueError instead of KeyError when the uid is wrong.

**Comment by itziakos** [comment]
I think that the behavior of is correct. `update_bond` and `update_particles` do not get a `key` as arguments (i.e. a uid), in this case I think that ValueError (https://docs.python.org/2/library/exceptions.html#exceptions.ValueError) is more appropriate

**Comment by itziakos** [comment]
However, I do not have very strong feeling about the issue, so if the collaborators feel that a `ValueError` is confusing then `KeyError` should be ok.

**Comment by nathanfranklin** [comment]
ValueError is fine.  

 I actually meant to say that it was raising KeyError instead of ValueError.  I had a note to myself to that effect (see https://github.com/simphony/simphony-lammps-md/blob/eeb1767850cfdab30088a885983b44bf8027e9ce/simlammps/tests/test_particle_container.py#L35-L42) but now that I test ParticleContainer, it does return ValueError and not KeyError. 

Sorry for the confusion. Problem was on my end.
