### ISSUE TITLE
Cleanup initialization of file related cuds containers

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#108]
This issue aims to address the following problems with the initialization of file related CUDS containers

- Currently `FileMesh` and `FileLattice`, require the pytables file handle for initialization. This is not necessary and should be replaced with requiring the pytables Group node similar to H5Particle. This will decouple the local structure of the Mesh or Lattice serialization from the overall file layout of the H5CUDS file.
- The current initialization supports both creating new and wrapping an existing container in the file.  This makes the initialization code a little confusing and unnecessary complicated. because we support two different behaviours with the same constructor. A common pattern in python is to split the behaviour into two constructors. The default constructor `__init__(group)` will initialize a proxy class from an existing structure, while the secondary constructor (i.e. a `classmethod`) named `create_new(group)` will be used for creating/reseting a CUDS container representation in the hdf5 file and then calling the primary constructor to initialize a proxy instance on top of the new group node.

**Comment by kemattil** [comment]
@tuopuu can you address this? Also, do you think this has any relevance to the "empty lattice problem" we have been discussing earlier?

**Comment by tuopuu** [comment]
@kemattil, I don't think the above changes would have any implications to usage or access to the classes. I can implement this enhancement later today to FileLattice class.

**Comment by itziakos** [comment]
We should do the same for IndexDataContainerTable and DataContainerTable

**Comment by tuopuu** [comment]
> We should do the same for IndexDataContainerTable and DataContainerTable

Agreed with @itziakos. I can work on that. It should go similarly to what I did with #109.

**Comment by itziakos** [comment]
#109 implements the logic for the Lattice H5backend

**Comment by itziakos** [comment]
> We should do the same for IndexDataContainerTable and DataContainerTable

I can pick-up the `IndexDataContainerTable` and `DataContainerTable` items but they will not arrive for milestone 0.1.2
