### ISSUE TITLE
Provide batch operations for adding multiple elements (e.g. particles/bonds)

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#11]
Please find below the proposed changes to the current CUDS api.

```python
class ABCLattice(self):

    def add_nodes(nodes):
        """ Add a set of nodes from the provided iterable.

        """

    def update_nodes(nodes):
        """ Update a set of nodes from the provided iterable.

        """

class ABCParticles(self):

    def add_particles(iterable):
        """ Add a set of particles from the provided iterable.

        """

    def update_particles(iterable):
        """ Update a set of particles from the provided iterable.

        """

    def remove_particles(iterable):
        """ Update a set of particles from the provided iterable.

        """

    def remove_particles(uids):
        """ Remove the particles with the provided uids.

        """

    def add_bonds(iterable):
        """ Add a set of bonds from the provided iterable.

        """

    def update_bonds(iterable):
        """ Update a set of bonds from the provided iterable.

        """

    def remove_bonds(uids):
        """ Remove the bonds with the provided uids.

        """

class ABCMesh(self):

    def add_points(iterable):
        """ Add a set of points from the provided iterable.

        """

    def update_points(iterable):
        """ Update a set of points from the provided iterable.

        """

    def remove_points(uids):
        """ Remove the points with the provided uids.

        """

    def add_edges(iterable):
        """ Add a set of edges from the provided iterable.

        """

    def update_edge(iterable):
        """ Update a set of edges from the provided iterable.

        """

    def remove_edges(uids):
        """ Remove the edges with the provided uids.

        """

    def add_faces(iterable):
        """ Add a set of faces from the provided iterable.

        """

    def update_faces(iterable):
        """ Update a set of faces from the provided iterable.

        """

    def remove_faces(uids):
        """ Remove the faces with the provided uids.

        """

    def add_cells(iterable):
        """ Add a set of cells from the provided iterable.

        """

    def update_cells(iterable):
        """ Update a set of cells from the provided iterable.

        """

    def remove_cells(uids):
        """ Remove the cells with the provided uids.

        """
```

**notes**:
- Remove related methods are now provided for the Mesh container.
- All add operations return a list of uids of the items that where added in the order of the items in input.

**tasks**:
- [x] #175 
- [ ] #174 
- [x] #173

**Comment by nathanfranklin** [comment]
see proposal and related discussions at https://publicwiki-01.fraunhofer.de/SimPhoNy-Project/index.php/API_proposal:_CUDS_containers,_allow_iterable_input_for_add_xxx_and_update_xxx

**Comment by itziakos** [comment]
@roigcarlo, @nathanfranklin, @tuopuu, I have updated the description of the feature. Please have a look. We need to decide if we still need the single operation methods for now and remove them later or (preferably) remove them now so that the collaborators that move to 0.2.0 will only update their wrappers once.

**Comment by nathanfranklin** [comment]
> We need to decide if we still need the single operation methods for now and remove them later or (preferably) remove them now so that the collaborators that move to 0.2.0 will only update their wrappers once.

I prefer as well that we remove the single operations (i.e. ``add_particle``) now.

**Comment by roigcarlo** [comment]
Agree, I cannot see any reason to keep the old single entity operations.

**Comment by nathanfranklin** [comment]
Could the methods (i.e. ```add_particles```) be slightly changed to allow either an iterator or a single element as a parameter?  or would that look funny?

**Comment by itziakos** [comment]
@roigcarlo do you see any problem with providing remove operation for the mesh container?

**Comment by itziakos** [comment]
> Could the methods (i.e. add_particles) be slightly changed to allow either an iterator or a single element as a parameter? or would that look funny?

This has been already discussed in the wiki. To summarize, I prefer not to have such magic signature since it will make implementation (and probably debugging) a little more complicated without real gain, but I am not married to it.

**Comment by roigcarlo** [comment]
@itziakos It is ok for me. In fact I beleive is kind of odd that the method does not exist in the first place. The only reason for not implementing them is that they not appear in the original UML designs, but I think that nobody is going to complain if we just add it.

**Comment by itziakos** [comment]
> @itziakos It is ok for me. In fact I beleive is kind of odd that the method does not exist in the first place. The only reason for not implementing them is that they not appear in the original UML designs, but I think that nobody is going to complain if we just add it.

I agree
