### ISSUE TITLE
Should the attributes of the CUDS abstract base classes be abc.abstractproperty

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#121]
from @tuopuu and @kemattil:  

Should the lattice attributes (size, origin, data, etc.) be listed as abstract properties in ABCLattice?  What about the other (abstract) CUDS containers?

**Comment by kemattil** [comment]
Yes, I think they should be. And some (or most) properties can perhaps be even concrete properties (like ``name`` etc.)

**Comment by itziakos** [comment]
My preference is that they should not be, instead with should implement a custom https://docs.python.org/2/library/abc.html#abc.ABCMeta.__subclasshook__ to check for these properties

The main reason is that an abstract property does not allow attributes to be defined instead of get and setter methods.

**Comment by kemattil** [comment]
I'm not sure if I understand the reason, but if it is a more pythonic way, I'm ok with it.

**Comment by itziakos** [comment]
I would not say it is pythonic. Commonly in python we do not define abstract attrbiutes or properties (some time we do not define abstract classes at all). For some they are just syntactic sugar, for other is just something to make java and c++ developers happy. The pythonic way is to that developers are consenting adults and nothing is better than documentation and properly testing you code.


So the only reason for avoiding an `abstractproperty` to discribe a required attribute is the folloing example.

```python
class MyABC(class):

     @abstractproperty
      def data(self):
            pass

class MyClass(MyABC):

         def __init__(self):
               self.data = 3

my_class = MyClass()   # this will fail with error because MyABC aspected a property not a attribute.

```

(not understanding is not reason to agree with Ioannis :P, actually some friends say to always disagree with Ioannis).

**Comment by kemattil** [comment]
Yes, ```MyClass()``` should fail because it has not implemented the ```data``` property. I still don't see the inconvenience ...

However, like I mentioned in my comment, perhaps concrete properties for ```ABCLattice``` would be more appropriate (we have currently 4 lattice implementations of ```ABCLattice```, and we are just copy-pasting the same code, i.e. part of the initialization, properties and the ```get_coordinate``` method).

Hence, I would prefer something like

```python
class ABCLattice(object):
    __metaclass__ = ABCMeta

    def __init__(self, name, type, base_vect, size, origin):
        self.name = name
        self._type = type
        self._base_vect = np.array(base_vect, dtype=np.float)
        self._size = tuple(size)
        self._origin = np.array(origin, dtype=np.float)
        self._data = DataContainer()

    @property
    def type(self):
        return self._type

    @property
    def base_vect(self):
        return self._base_vect

    @property
    def size(self):
        return self._size

    @property
    def origin(self):
        return self._origin

    @property
    def data(self):
        return DataContainer(self._data)

    @data.setter
    def data(self, value):
        self._data = DataContainer(value)

    def get_coordinate(self, index):
        if self._type == 'Hexagonal':
            raise NotImplementedError("""Get_coordinate for
                Hexagonal system not implemented!""")
        return self.origin + self.base_vect*np.array(index)

    @abstractmethod
    def get_node(self, index):

    @abstractmethod
    def update_node(self, lat_node):

    @abstractmethod
    def iter_nodes(self, indices=None):
```

And then

```python
class Lattice(ABCLattice):

    def __init__(self, name, type, base_vect, size, origin):
        super(Lattice, self).__init__(self, name, type, base_vect, size, origin)
        self._dcs = np.empty(size, dtype=object) # Node related data

    def get_node(self, index):
        ...

    def update_node(self, lat_node):
        ...

    def iter_nodes(self, indices=None):
        ...
```

**Comment by tuopuu** [comment]
H5_Lattice does not fit into that model anymore since we separated create_new method/functionality from __init__. For H5_Lattice we would have to overload __init__ completely.

It's a good point, though, to try to use same code for the parts where it's possible. Perhaps it could be done just to the methods...

**Comment by kemattil** [comment]
Why doesn't it fit to the above model? For example

```Python
class H5Lattice(ABCLattice):
    def __init__(self, group):
        super(H5Lattice, self).__init__(self, group._v_name, group.lattice.attrs.type,
          group.lattice.attrs.base_vect, group.lattice.attrs.size, group.lattice.attrs.origin)

        self._group = group
        self._table = IndexedDataContainerTable(group, 'lattice')
        self._data = IndexedDataContainerTable(group, 'data')
```
Am I missing something?

**Comment by kemattil** [comment]
Please note also that if the [ABCLattice API proposal](https://publicwiki-01.fraunhofer.de/SimPhoNy-Project/index.php/ABCLattice_api_proposal) will be implemented, the primitive vectors (attributes/properties replacing the base vector) should be assigned at the initializator/constructor of the ABCLattice (too much new code to copy-paste around).

**Comment by itziakos** [comment]
> Yes, MyClass() should fail because it has not implemented the data property. I still don't see the inconvenience ...

Looking at your example, is see the confusion.

So, in python `object.name` attribute access can happen for an instance in a number of ways (see https://docs.python.org/2/reference/datamodel.html#customizing-attribute-access). The `property` decorator defines a data-descriptor, so when we use the `abstractproperty` decorator we do not only state that `object.name` should exist but also that it has to exist as a `property` definition. This is general might be to restrictive (which personally I am not very fond of).

However, in the particular case were you want all attributes to be readonly using a property is the logical way of implementing the attribute. Furthermore, if using `abstractproperties` addition helps scientists and developers from other languages understand better what they need to implement then we should follow that policy.

**Comment by kemattil** [comment]
Thank you for this explanation: the consequences of using the ```abstractproperty``` in base classes is now much more clear to me.

**Comment by itziakos** [comment]
No worries and sorry for the confusion.
