### ISSUE TITLE
hdf5 requirement

### ISSUE THREAD

**Issue by jeremy-rutman** [simphony/simphony-common#143]
I blv that hdf5 should be listed as  a requirement for simphony-common, at least to pass the unit tests
e.g. on a rhel machine without hdf5, 
python2.7 -m unittest discover 
hits 8 unittest errors all of the form 
ImportError: libhdf5.so.9: cannot open shared object file: No such file or directory

**Comment by itziakos** [comment]
hdf5 is a requirement of PyTables, which itself is an optional requirement for simphony-common when the native io functionality is needed (see https://github.com/simphony/simphony-common/blob/master/README.rst#requirements). What we should do is to skip the related tests (notifying the user ofcourse) when pytables is not available.

**Comment by roigcarlo** [comment]
Implemented on #166
