### ISSUE TITLE
Duplicate hdf5 groups of the CUDS containers

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#148]
reported by @roigcarlo 

In general, each time that a container is generated here ( for the mesh case for example ):
https://github.com/simphony/simphony-common/blob/master/simphony/io/h5_cuds.py#L211

Specifically, this error is being triggered by

test_add_get_mesh
test_mesh_rename
test_iter_mesh
test_delete_mesh
So I assume that this is happening because the python get_xxx() functions of h5_cuds.py are returning the container by copy. This does not cause problems if the original objects is "normal" object, since the group does not exist, but when python group = self._root.mesh._f_get_child(name) is not empty it duplicates the groups.

I have been able to duplicate this as well with the h5_lattice class, and it looks that h5_particles is going to behave the same way

**Comment by itziakos** [comment]
@roigcarlo, I run the `test_iter_mesh` but I cannot see the duplicate hdf5 groups
```
c:\users\itziakos\appdata\local\temp\tmpgtjpxa\test.cuds (File) u''
Last modif.: 'Fri Jun 19 13:18:58 2015'
Object Tree: 
/ (RootGroup) u''
/lattice (Group) 'lattice'
/mesh (Group) 'mesh'
/particle (Group) 'particle'
/mesh/test_0 (Group) ''
/mesh/test_0/cells (Table(0,)) ''
/mesh/test_0/data (Table(1,)) ''
/mesh/test_0/edges (Table(0,)) ''
/mesh/test_0/faces (Table(0,)) ''
/mesh/test_0/item_data (Table(0,)) ''
/mesh/test_0/points (Table(0,)) ''
/mesh/test_1 (Group) ''
/mesh/test_1/cells (Table(0,)) ''
/mesh/test_1/data (Table(1,)) ''
/mesh/test_1/edges (Table(0,)) ''
/mesh/test_1/faces (Table(0,)) ''
/mesh/test_1/item_data (Table(0,)) ''
/mesh/test_1/points (Table(0,)) ''
/mesh/test_2 (Group) ''
/mesh/test_2/cells (Table(0,)) ''
/mesh/test_2/data (Table(1,)) ''
/mesh/test_2/edges (Table(0,)) ''
/mesh/test_2/faces (Table(0,)) ''
/mesh/test_2/item_data (Table(0,)) ''
/mesh/test_2/points (Table(0,)) ''
/mesh/test_3 (Group) ''
/mesh/test_3/cells (Table(0,)) ''
/mesh/test_3/data (Table(1,)) ''
/mesh/test_3/edges (Table(0,)) ''
/mesh/test_3/faces (Table(0,)) ''
/mesh/test_3/item_data (Table(0,)) ''
/mesh/test_3/points (Table(0,)) ''
/mesh/test_4 (Group) ''
/mesh/test_4/cells (Table(0,)) ''
/mesh/test_4/data (Table(1,)) ''
/mesh/test_4/edges (Table(0,)) ''
/mesh/test_4/faces (Table(0,)) ''
/mesh/test_4/item_data (Table(0,)) ''
/mesh/test_4/points (Table(0,)) ''
```


**Note**:
I agree however with you that https://github.com/simphony/simphony-common/blob/master/simphony/io/h5_cuds.py#L211 looks agly and should be fixed.

**Comment by roigcarlo** [comment]
@itziakos I am not able to reproduce the error and everythong seems to work fine. So I assume I had some local change that was altering the results. We can close this and reopen the issue if I am able to replicate the error once more.

**Comment by itziakos** [comment]
ok, thanks
