### ISSUE TITLE
Consistent identification (id/uuid) for parameters/attributes in Particle/Point/etc

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#20]
In Mesh and ParticleContainer hold entities (e.g. Particles, Points, Edges) which have a means of identification.  That identification is used when getting, updating or adding such entities to the high-level objects (Mesh, ParticleContainer).    

This identification should have a consistent name across the classes. Currently, `id` is used as an attribute to Particle/Point/Edge/Cell.  
However in the __init__ methods there are currently some differences:
 *  `id` is used as a parameter in Particle. 
 *   `uuid` is used as a parameter in Point, Edge, Face, and Cell

Example:

from simphony.cuds.mesh import Point
from simphony.cuds.particles import Particle

particle = Particle(**id**=None, coordinates=(0.0, 0.0, 0.0))
point = Point(**uuid**=None, coordinates=(0.0, 0.0, 0.0))

**Comment by itziakos** [comment]
I think it is time to take a vote on the issue. I vote for `uid` based on the https://github.com/simphony/simphony-common/issues/20#issuecomment-67320388

**Comment by nathanfranklin** [comment]
`uid`  :+1:

**Comment by roigcarlo** [comment]
`uid` as well

**Comment by SGGgarcia** [comment]
`uid` sounds good

**Comment by itziakos** [comment]
I am picking this up

**Comment by itziakos** [comment]
work for this milestone done in #61. Moving to next milestone

**Comment by itziakos** [comment]
This has been implemented
