### ISSUE TITLE
problem using test_delete_dataset and test_iter_dataset in CheckEngine

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#219]
`test_delete_dataset` uses ds.name after ds has been deleted.  It also remove datasets while iterating over the datasets.

`test_iter_dataset` assumes that  `iter_dataset` returns the datasets in the order that they were added.

**Comment by nathanfranklin** [comment]
Closed by #220

**Comment by tuopuu** [comment]
I'll reopen this issue, because ```test_delete_dataset``` still references the proxy object and therefore the object is not deleted. See my previous line comment.

**Comment by nathanfranklin** [comment]
@tuopuu , we can close this again, right?

**Comment by tuopuu** [comment]
Yes, we can close this.
