### ISSUE TITLE
Implementation of FileMesh class

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#22]
"Task 2:  Definition of hdf5 file format for storing mesh.    Implementation of using the defined hdf5 file format to read/write mesh "

**Comment by itziakos** [comment]
@roigcarlo, `https://github.com/simphony/simphony-common/tree/feature-mesh-io` branch ready for review?

**Comment by roigcarlo** [comment]
@itziakos There are two issues
* 1st, we haven't decided yet what to do about the number of points of the elements, we can discuss it in the PR.
* 2nd, It does not store the data form the points / elements. This should be done with https://github.com/simphony/simphony-common/pull/31 right?

Apart from that yes, it is ready. If you are ok with It I'll make the PR.

**Comment by itziakos** [comment]
> 1st, we haven't decided yet what to do about the number of points of the elements, we can discuss it in the PR.

One choice is to have a maximum number of points (similar to how the particle file io works) but I believe that a separate VLArray holding the ids for each point is better. In that case the points column contains an Int that points to the VLArray row where the uuids of the contained points are stored. 
The only downside of this setup is that deleting `elements` will not delete them from the VLArray. However, this is not a big problem.

**Comment by itziakos** [comment]
> 2nd, It does not store the data form the points / elements. This should be done with #31 right?

Yes #31 provides a simple container that holds a table of DataContainers.

**Comment by itziakos** [comment]
> Apart from that yes, it is ready. If you are ok with It I'll make the PR.

Yes, please make a `WIP` PR (i.e. add [WIP] to the PR title) and make sure that there are open issues for the items that are blocking your implementation. Is it always easier to discuss the issues based on an implementation.

**Comment by itziakos** [comment]
This might be useful http://pytables.github.io/usersguide/libref/homogenous_storage.html?highlight=vlarray#tables.VLArray

**Comment by nathanfranklin** [comment]
Closed by #36
