### ISSUE TITLE
`supported_cubas` optional initialization argument for Mesh/Lattice/Particles

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#223]
This issue covers the optional initialization argument for Mesh/Lattice/Particles from @itziakos :  https://publicwiki-01.fraunhofer.de/SimPhoNy-Project/index.php/Supported_CUBA_keys_for_container .  (Note that the other points from this proposal are covered in #217)
- The Mesh, Particles and Lattice objects should accept at initialization an optional argument passing a set of cuba values that will be supported. Default values for the supported cuba keys for each container type should be decided by the related workgroups and the SSB. 

```
mesh1 = Mesh(name='test1', supported_cubas={CUDSItem.POINT:set(CUBA.VELOCITY), CUDSItem.CELL:set(CUBA.COLOR)})
```

Description of what needs to be done is being disussed also on the wiki.

**Comment by stefanoborini** [comment]
No longer relevant. We don't constrain anymore.
