### ISSUE TITLE
Extend documentation to describe basic steps to write an engine-wrapper

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#225]
@ahashibon :   We currently have some information on plugins (see https://github.com/simphony/simphony-common/blob/36e8a752250b0495f5ee03ff6f42d48368b1bcf9/doc/source/plugins.rst) and engines (`ABCModelingEngine`).  But we need to have a guide that helps people write a new engine-wrapper.  This should be targeted to an audience who unfamiliar with SimPhoNy

**Comment by mehdisadeghi** [comment]
This is being addressed with more docs on writing wrappers with metadata support. Anything specific will be handled when necessary.
