### ISSUE TITLE
add MaterialRelation

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#226]
See https://publicwiki-01.fraunhofer.de/SimPhoNy-Project/index.php/MaterialRelations_proposal

The MaterialRelation class has the following attributes:
    * name: a unique string name to identifying instances of these classes.
    * description: a user-defined description string
    * parameters: DataContainer containing the required parameters
    * supported_parameters: read-only attribute contains what CUBA values are required/allowed for the parameters
    * materials: list of uids of materials where this relation applies
    * kind: read-only attribute having a type CUBA which describes what kind of MaterialRelation this is (and subsequently what the supported_parameters are and what is the acceptable length(s) of the materials list). 

This requires: 
- [ ] Adding `MaterialRelation` class
- [ ] Adding tests and documentation
- [ ] Creating a `SP` object to contain these material relations (i.e. `add_material_relation`, `get_material_relation`, `delete_material_relation`, `update_material_relation`) (plus tests and documentation)

**Comment by ahashibon** [comment]
Hold on with the SP!

**Comment by nathanfranklin** [comment]
@roigcarlo , I see your branch where you started this work and there are some questions listed there. do you want to skype about this (i have time on Friday or Tuesday)?    Additionally, you can hold off on adding the material relations related to molecular dynamics (and related CUBA keywords) as I will cover those in #236  (LennardJones etc..)

**Comment by roigcarlo** [comment]
Hi @nathanfranklin In fact I was planning to discuss that tomorrow during the meeting, or maybe later sure ( it shouldn't have been uploaded : P).
I'm not going to add any other material relation but I need a couple of classes in order to test that everything is working fine. 

Once I have some initial tests done I will make a PR and we can keep the discussion there with the code.

**Comment by nathanfranklin** [comment]
Sounds good!

**Comment by nathanfranklin** [comment]
Closed by #253
