### ISSUE TITLE
Implementation of FileLattice class

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#23]
"Task 2: Definition of hdf5 file format for storing mesh. Implementation of using the defined hdf5 file format to read/write a lattice mesh "

**Comment by itziakos** [comment]
@tuopuu what is the status of `https://github.com/simphony/simphony-common/tree/file_lattice` is it ready for review?

**Comment by tuopuu** [comment]
@itziakos Unit tests are still missing, but I'll finish that off asap. After that it's good.

**Comment by itziakos** [comment]
I would suggest to create a WIP PR (i.e. a PR whose title starts with [WIP]) and add the pending tasks in the description (see example #31)

**Comment by roigcarlo** [comment]
Completed in https://github.com/simphony/simphony-common/pull/74
