### ISSUE TITLE
ReadtheDocs documentation is not built properly

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#235]
The code reference in 0.2.1 is broken. (compare http://simphony.readthedocs.org/en/0.2.1/api/cuds.html
with http://simphony.readthedocs.org/en/0.2.0/). The api reference of the modules is missing

**Comment by itziakos** [comment]
extract of the recent build can be found in http://readthedocs.org/projects/simphony/builds/3492438/

**Comment by nathanfranklin** [comment]
Is this issue covered in #213 and #214?

**Comment by itziakos** [comment]
yup the issue is still there in the current master http://readthedocs.org/projects/simphony/builds/3511737/

Does the documentation look ok locally?

**Comment by nathanfranklin** [comment]
Yeah, it looks fine locally: 
![cuds_html1](https://cloud.githubusercontent.com/assets/8287580/11366135/b1514c18-92ab-11e5-8d48-b9b96cab2409.png)

**Comment by itziakos** [comment]
then there is something that broke with the ReadTheDoc setup

**Comment by mehdisadeghi** [comment]
I made an alternative readthedoc on my rtd account to investigate the issue. As expected it was broken, however changing the advanced settings of the project fixed the issue for me. Here is the settings that I used:
![snapshot1](https://cloud.githubusercontent.com/assets/3101557/11659555/36d95e34-9dc9-11e5-8aa1-0fd4054dcbb5.png)

What is the project settings in the readthedocs?

**Comment by itziakos** [comment]
Sometimes the readthedocs enviroment becomes broken so one will need to `wipe` problematic version builds and rebuild them. I have done the wipe and it looks that it is ok now.
