### ISSUE TITLE
Mesh.get_point, get_edge, get_face, get_cell functions are creating new Instance?

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-common#239]
May I ask why `Mesh.get_point` function creates a new `Point` instance using `Point.from_point` while `self._point[uid]` is already a `Point` instance?  (similarly for `Mesh.get_edge` etc)

**Comment by roigcarlo** [comment]
Hi Kit,

We always return a new copy to avoid people to directly modify the object, in this case the mesh.
This is true also or Particles and Lattice.

**Comment by itziakos** [comment]
We have been calling this the snapshot principle http://simphony.readthedocs.org/en/master/cuds_definition.html

**Comment by kitchoi** [comment]
Brilliant!  Thank you!
