### ISSUE TITLE
change dtype from uuid to uuid.UUID

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#248]
change dtype from uuid to uuid.UUID
e.g:
 https://github.com/simphony/simphony-common/blob/master/simphony/core/keywords.py#L564

**Comment by nathanfranklin** [comment]
@kitchoi , is this correct?

**Comment by kitchoi** [comment]
Yep, and I meant `uuid.UUID` (class), not `"uuid.UUID"` (str)

**Comment by kitchoi** [comment]
@nathanfranklin I was testing this out and I also found a bug.  Please take a look at the pull request #250

**Comment by nathanfranklin** [comment]
closed by #250
