### ISSUE TITLE
CUDS api extension: Shared data

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#25]
There is a need to share common data within groups of cuds components especially sharing some of the values in data containers. This is expected to improve memory usage.

**Comment by ahashibon** [comment]
We need to carefully examine all requirements for grouping and sharing properties in general. Grouping in general is also needed for BC, SP, and CM, not only for SD components. (sorry, clicked the wrong button earlier, did not really meant to close the issue)

**Comment by roigcarlo** [comment]
This is now in #226 and #227
