### ISSUE TITLE
CUBA.NUMBER_OF_TIME_STEPS is currently a float

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-common#271]
Should `NUMBER_OF_TIME_STEPS` be int instead?
Current dtype for [`NUMBER_OF_TIME_STEPS` is float64](https://github.com/simphony/simphony-common/blob/master/simphony/core/keywords.py#L406)
Just been trying to run animations with kratos and mayavi and then got an error that the type is wrong.  Kratos expects `Int`.  The two should be consistent.

**Comment by nathanfranklin** [comment]
yeah, 'int' seems correct.

**Comment by roigcarlo** [comment]
Agree as well.

I can make the wrapper work with float64 as well, but I suppose int makes more sense

**Comment by ahashibon** [comment]
number of time steps should always be interger.
