### ISSUE TITLE
Create a new API for generated clasess

### ISSUE THREAD

**Issue by roigcarlo** [simphony/simphony-common#282]
We should discuss which are going to be the modules and where to put the files for the generated classes API.

**Comment by kitchoi** [comment]
We now have the generated classes and an api.py in simphony/cuds/meta

**Comment by mehdisadeghi** [comment]
@kitchoi Since this issue was about where to put classes, I will close this one and open another issue for the defining a common functionality API of the meta classes.

fixed in #300
