### ISSUE TITLE
"name" attribute for all high-level cuds objects

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#30]
On the wiki, it was suggested that high-level cuds objects have a name attribute.

**Comment by ahashibon** [comment]
Here is a user prespective: 
There are cases when a modeler would change the name of a particle container, for example to designate a new state, that is substantially different than an initial one. I do not see yet the advantage of a read only name. It will be the users responsibility to give unique meanningful names, and therefore also change them as needed with out the need to clone data.

**Comment by nathanfranklin** [comment]
yes,  sounds like we are all in agreement of a the `name` attribute as read/write.  

@itziakos , @ahashibon ,  can I open a new issue which would just say:   "add 'name' attribute to high-level cuds objects".    I would then link to this issue in the new issue and then close this issue.

 I am suggesting this cause I think in this issue, I cause the discussion on tangent because I was thinking about CudsFile and the wrapper interface.  All the comments here ight be confusing for people that read this later.

**Comment by itziakos** [comment]
> @itziakos , @ahashibon , can I open a new issue which would just say: "add 'name' attribute to high-level cuds objects"?

fine by me

**Comment by nathanfranklin** [comment]
replaced by #38
