### ISSUE TITLE
Appveyor build fails due to flake8 known bug

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-common#306]
Example failed build: https://ci.appveyor.com/project/itziakos/simphony-common/build/1.0.478
Known issue on appveyor for flake8 3.0.0 and 3.0.1: https://gitlab.com/pycqa/flake8/issues/179 and https://gitlab.com/pycqa/flake8/issues/184

**Comment by kitchoi** [comment]
For reference, apparently calling `cmd ".\appveyor-install.cmd"` in appveyor.yml removes `!` inside ".\appveyor-install.cmd"
https://github.com/simphony/simphony-common/compare/appveyor-flake8-no-3.0.x

**Comment by stefanoborini** [comment]
We are now using flake < 3. Closing
