### ISSUE TITLE
Define API of meta classes in a common base class

### ISSUE THREAD

**Issue by mehdisadeghi** [simphony/simphony-common#309]
The data structure of all meta classes is defined in metadata repository. However, we need to define the functionalities of these classes as well.

**Comment by stefanoborini** [comment]
I think I understand what you mean, but could you please expand a bit more?

**Comment by stefanoborini** [comment]
The new generator provides and uses inheritance for its methods. This simplifies the generated class considerably. If I understood the request correctly, this is done.

**Comment by stefanoborini** [comment]
Closing. This is now addressed
