### ISSUE TITLE
Make sure that meta objects are immutable

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#313]
It is important for low level objects like the ones in `simphony.meta` to be immutable  for example there is not real reason why the `vector` attributes is not a tuple in this case of the `Box` 

https://github.com/simphony/simphony-common/blob/master/simphony/cuds/meta/box.py

**Comment by stefanoborini** [comment]
This data is represented as numpy entities, and there's pretty much nothing we can do. If the data is a large matrix, it must be a numpy array, and therefore it must be mutable.
Closing.
