### ISSUE TITLE
Merge legacy CUDSItem into keywords or CUBA

### ISSUE THREAD

**Issue by mehdisadeghi** [simphony/simphony-common#316]
Regarding the new metadata schema, the following class is redundant and should be merged into metadata (into keywords or CUDS).

```
class CUDSItem(IntEnum):

    POINT = 0
    PARTICLE = 1
    BOND = 2
    EDGE = 3
    FACE = 4
    CELL = 5
    NODE = 6

```

**Comment by SGGgarcia** [comment]
As I think this was only meant to be used for the `count_of` methods in the lattice, mesh, particles and their respective ABCs, we can:
- Rename this class as it has the same name that the real CUDSItem class, or
- Modify the high cuds components and change the `count_of` methods so they recieve a keyword instead
I prefer the second one, and get rid of this

**Comment by mehdisadeghi** [comment]
Yes, exactly. I only found it in `cound_of` methods. And I also agree with the second approach.

**Comment by stefanoborini** [comment]
This is done, and we can close it.
