### ISSUE TITLE
Generated meta files are faulty

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-common#330]
It is my understanding (see #329 comments) that the python files generated by the automatic generator are faulty, and needs to be patched by hand. This is not good, and needs to be fixed as soon as possible. If you have anything historical that may help me in understanding the context of this, please write it as a comment.

**Comment by mehdisadeghi** [comment]
I'm not sure about the `shape` properties yet, but `MATERIAL_ID` should be removed from simphony alltogether.

**Comment by stefanoborini** [comment]
@mehdisadeghi @ahashibon please let me know ASAP, because this needs fixing before I merge #329. Right now tests are not passing against the recent metafiles.

**Comment by mehdisadeghi** [comment]
Both issues are resolved. No patching is necessary anymore. #331 simphony/simphony-metadata#52
