### ISSUE TITLE
RestrictedDataContainer needed?

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-common#333]
So, there's a function in data_container, called create_data_container. It actually creates a new _class_ derived from DataContainer, with defined restricted keys. I am unsure of the logic behind it, but to me it seems redundant and pointless. What this function should eventually do is to instantiate an (empty) DataContainer with the proper restricted keys as specified.

**Comment by kitchoi** [comment]
It is no longer used and is made redundant.  Instead I think we can add a class method to DataContainer that instantiate a DataContainer with the restricted keys.

**Comment by stefanoborini** [comment]
Ok, thanks. The conclusion is that I will remove the method, and put a classmethod constructor to set specific restricted keys at creation.

**Comment by kitchoi** [comment]
SGTM.  Thanks.

**Comment by mehdisadeghi** [comment]
Done in #334
