### ISSUE TITLE
Change of CUBA enumeration values breaks compatibility

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-common#339]
I just observed that the CUBA enumeration values change. This is _BAD_, because these values uniquely identify the meaning of that key. If the value changes, the meaning changes too if it gets persisted and retrieved. This means that any change to the meta files can completely break compatibility, even a simple addition at the end of the file. This is because the traversal may introduce the new entity in the middle of the cuba list, effectively shifting all entries down one value.

**Comment by mehdisadeghi** [comment]
What if we use unique string values instead?

**Comment by stefanoborini** [comment]
Working on this.
