### ISSUE TITLE
add ABCModelingEngine to simphony/cuds

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#47]
https://publicwiki-01.fraunhofer.de/SimPhoNy-Project/index.php/Wrapper_description#Interface_for_wrapper_to_a_modeling_engine

**Comment by itziakos** [comment]
I think that the name should be `ABCModelingEngine`

**Comment by kemattil** [comment]
I agree, ABCModelingEngine is a better name.
