### ISSUE TITLE
Nature of a Boundary Condition

### ISSUE THREAD

**Issue by jamartik** [simphony/simphony-common#53]
Here's something for you to comment:

I would say that we can specify the type of the boundary condition as some kind of agreed key instead of trying to describe the equational form of the exact condition. The former is by far easier and for the same type of a boundary there may be several ways to implement it. For example, the wall condition for the turbulent kinetic energy is usually either a (nonlinear) Dirichlet type condition or a no-flux (homogeneous Neumann) condition with special boundary layer source term. The exact implementation should be irrelevant for the user, hence the same key.

The boundary condition, of course, needs the specification of the boundary... and we have the uuids. For me, it would make most sense to give the uuids of the boundary faces (in 3D), since the whole boundary is then uniquely defined and from the faces it is easy to get all the nodes or edges. Anyway, a list (or something) of uuids should be sufficient.

Then the values. I have understood that some of the codes like to have the nodal values specified. OpenFOAM, on the other hand, needs the face center values. As a generalization, the boundary condition should be able to give a value for any specified point on the boundary. We probably could make value-giving classes (for possible multiple values needed by the boundary condition) inside boundary condition class, having build in value interpolation routines from nodal or face centered data to any point. The point specification could be barycentric coordinates of an edge or face and the corresponding uuid. The barycentric coordinates are easily transformed (also build in) to ordinary eulerian coordinates, to support analytical expressions, for example.

The variable for which the boundary condition is applied could be given as CUBA key(s).

What slightly bothers me with all this is that when several boundary conditions act on the same boundary for different variables, we end up repeating the same list of uuids to specify the boundary. To avoid this, we would need separate entieties for boundary and boundary condition.

**Comment by ahashibon** [comment]
Let us move this discussion to the internal wiki, it is still premature to start it here. 
check this page:
https://publicwiki-01.fraunhofer.de/SimPhoNy-Project/index.php?title=SimPhoNy_Model_Component:_Boundary_Conditions&action=edit

**Comment by mehdisadeghi** [comment]
According to the last commit and presence of wiki and metadata repository, this discussion can be followed either on the wiki or on the metadata repository. Therefore I close this issue. Feel free to re-open if you fee it is necessary.
