### ISSUE TITLE
Make a feature release

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#75]
The following tasks are the necessary for make a new feature release of `simphony-common`

- [x] Make a release preparation PR to:
 - update the version in `setup.py` to the release version e.g. `0.1.0.dev0` -> `0.1.0`. It should probably be    updated in the `conf.py` for the documentation. 
 - Update changes in the CHANGES.txt (if there is no such file we need to create it). See example in https://github.com/enthought/traits-enaml/blob/master/CHANGES.txt
- [x] As soon as the preparation PR is merged make the release in github (see https://help.github.com/articles/creating-releases/)
- [x] make a post release PR to:
  - update the version in `setup.py` and other places to the next milestone version e.g. `0.1.1.dev0`
- [x] Sent an e-mail to collaborators to notify of the new release attaching the changes that it brings to the library.

**Comment by itziakos** [comment]
@roigcarlo , I am assigning this to you let me know if you have any questions.

**Comment by roigcarlo** [comment]
:+1:
