### ISSUE TITLE
Add a ABCCheckMeshContainers testing template

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#77]
This new class will be similar to the ABCCheckParticlesContainers template class and will allow easier integration and more reliable testing of the multiple implementations (native or adapter) of the ABCMesh api.

**Comment by itziakos** [comment]
@roigcarlo and @nathanfranklin, I do not think, I will have time to implement (including time for review) this issue this week. Can we move this issue to the next milestone?

**Comment by roigcarlo** [comment]
Sure, moved.

**Comment by itziakos** [comment]
Thanks @roigcarlo.

**Comment by nathanfranklin** [comment]
closed by #134
