### ISSUE TITLE
Tests: Lattice tests do not set the size attribute correctly

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#79]
The lattice tests for the lattice factory functions set the size of the lattice defined in 3D to a 2D size (see
https://github.com/simphony/simphony-common/blob/master/simphony/cuds/tests/test_lattice.py#L58)

I also think that the factory tests need to be a little more thorough (e.g. test that number of lattice nodes is the expected one).

**Comment by roigcarlo** [comment]
Dear @kemattil, @tuopuu  Do you mind to take this for the release 0.2.0?

**Comment by itziakos** [comment]
@roigcarlo and @tuopuu  this issues is addressed  by #106

**Comment by itziakos** [comment]
fixed in #106
