### ISSUE TITLE
CUDS: Lattice size, origin and base_vectors should be always in 3D 

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#80]
This will allow defining lattices that are in the XY, YZ, XZ planes. Such lattices will be also easier to visualized next to full 3D lattice instances.

**Comment by kemattil** [comment]
There is now a SSB decision on this (teleconference on 17th April, see point 2.2 in meeting minutes at https://publicwiki-01.fraunhofer.de/SimPhoNy-Project/images/f/fd/Minutes_SSB_20150417.pdf).

That is, SimPhoNy deals only with 3D models. Hence, lattice attributes and method arguments should be in 3D (including node indexes).

**Comment by itziakos** [comment]
Thanks @kemattil, this is now an approved feature extension.
