### ISSUE TITLE
The native python implementation for the Particles container does not support properly the `data` attribute

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#84]
`data` should probably be a property so that getting and setting the information take place through a copy.

**Comment by nathanfranklin** [comment]
> data should probably be a property so that getting and setting the information take place through a copy.

just to clarify this for myself (and also for anyone new to this discussion),  we want to avoid the situation where a user could do the following:

```
pc = Particles(name="foo")
data=pc.data
# user changes data and has now changed the data
# of the high-level object particles 
data[CUBA.RADIUS] = 42
print(pc.data[CUBA.RADIUS])
```

So we have `data` now as a property so one would need to do:
 ```
pc = Particles(name="foo")
data = pc.data
data[CUBA.RADIUS] = 42
pc.data = data
print(pc.data[CUBA.RADIUS])
```
 
instead of the previous way:
```
# no longer allowed
pc = Particles(name="foo")
pc.data[CUBA.RADIUS] = 42
print(pc.data[CUBA.RADIUS])
```

**Comment by itziakos** [comment]
Yes, this is how the file based CUDS objects behave. I still think that we might want to use ``data()`` and ``set_data()`` to make it clear that the information is a snapshot of the internal data but this should probably go through a discussion in the wiki.

**Comment by nathanfranklin** [comment]
> Yes, this is how the file based CUDS objects behave.

all the high-level objects  (i.e. ABCParticles, ABCMesh, ABCLattice) should all behave this way. right? 

> I still think that we might want to use data() and set_data() to make it clear that the information is a snapshot of the internal data but this should probably go through a discussion in the wiki.

Sounds good

I am not sure but wonder if this discussion would relate to the CM, SP, BC of ABCModelingEngine (as they are *at the moment* similar and so similar behavior might be expected).

**Comment by itziakos** [comment]
> I am not sure but wonder if this discussion would relate to the CM, SP, BC of ABCModelingEngine (as they are at the moment similar and so similar behavior might be expected).

They touch, but do not have to use the same solution or be solved at the same time.

**Comment by itziakos** [comment]
> all the high-level objects (i.e. ABCParticles, ABCMesh, ABCLattice) should all behave this way. right?

Based on the api description yes. I created separate issues so that it will be easier to distribute the work
