### ISSUE TITLE
consistent naming of classes in H5IO 

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-common#88]
we currently have:
H5CUDS
H5Particles
FileMesh
FileLattice (in PR)

We should rename things so they are consistent.

**Comment by itziakos** [comment]
I think that the H5... naming should is preferable

**Comment by nathanfranklin** [comment]
Agree.

**Comment by itziakos** [comment]
the Lattice io wrappers have been updated according to this issue in #109

**Comment by roigcarlo** [comment]
Mesh wrappers updated in PR https://github.com/simphony/simphony-common/pull/110
