### ISSUE TITLE
Lattice.get_coordinates does not properly support 'hexagonal' lattices

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#94]
looking at the implementation of  Lattice.get_ccordinates https://github.com/simphony/simphony-common/blob/master/simphony/cuds/lattice.py#L116 it looks that providing the x,y,x coordinates of hexagonal lattice nodes is not supported. 

Given that the Lattice api is going to change soon, I suggest to raise a ``NotImplementedError`` in when ``Lattice.type == 'Hexagonal'`` to make sure that user are informed of the current issue.

**Comment by roigcarlo** [comment]
@tuopuu Can you pick this up for the next milestone?

**Comment by nathanfranklin** [comment]
@kemattil , see @roigcarlo 's comment above

**Comment by itziakos** [comment]
It looks that the hdf5 implementation of the Lattice also suffers from this problem

**Comment by tuopuu** [comment]
Yes, I can pick this one up. We're going to work on number of issues in the Lattice systems.

**Comment by kemattil** [comment]
@tuopuu, for fixing this issue, add only the NotImplementedError. Before implementing/fixing the other issues, we have to discuss them in SSB (I'm preparing a memo).

**Comment by itziakos** [comment]
removing SSB label since the related API changes to the Lattice description have been approved

**Comment by itziakos** [comment]
provisional get_coordinates calculation provided by #163
