### ISSUE TITLE
DOC: Include a table of current CUDS keywords

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#96]
We should be able to use the yml file description of the CUDS keywords and generate an rst file with the table to include in our documentation. 

As a first step we could add the functionality into cuba_generate.py 
e.g.
```
cuba_generate rst  cuba.yml cuba.rst
```

So that we can generate the CUDS keywords table in rst format.

**Comment by nathanfranklin** [comment]
closed by #123
